config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'diaries#index'
  resources :diaries do
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :diary
  belongs_to :user
end

app/models/diary.rb
class Diary < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_one_attached :image

  with_options presence: true do
    validates :day
    validates :weight
    validates :sugar
    validates :protein
    validates :calorie
    validates :lipid
  end

  with_options format: { with: /\A[0-9]+(\.[0-9]+)?\z/, message: "は半角数字" } do
    validates :weight
    validates :sugar
    validates :protein
    validates :calorie
    validates :lipid
  end

  def self.search(search)
    if search != ""
      Diary.where('day LIKE(?)', "%#{search}%")
    else
      Diary.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :diaries
  has_many :comments

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'は半角英数字のみ'

  with_options presence: true do
    validates :nickname
    validates :initial_weight
    validates :target_weight
  end

  with_options format: { with: /\A[0-9]+(\.[0-9]+)?\z/, message: "は半角数字のみ" } do
    validates :initial_weight
    validates :target_weight
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :initial_weight, :target_weight])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/diaries/#{comment.diary.id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, diary_id: params[:diary_id])
  end
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :set_diary, only: [:edit, :show]
  before_action :move_to_index, except: [:index, :show, :search]

  def index
    @diaries = Diary.includes(:user).order("created_at DESC")
  end

  def new
    @diary = Diary.new
  end

  def create
    @diary = Diary.create(diary_params)
    if @diary.valid?
      @diary.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    diary = Diary.find(params[:id])
    diary.destroy
  end

  def edit
  end

  def update
    diary = Diary.find(params[:id])
    diary.update(diary_params)
  end

  def show
    @comment = Comment.new
    @comments = @diary.comments.includes(:user)
  end

  def search
    @diaries = Diary.search(params[:keyword])
  end
  
  private
  def diary_params
    params.require(:diary).permit(:day, :image, :weight, :sugar, :protein, :calorie, :lipid, :exercise, :comment).merge(user_id: current_user.id)
  end

  def set_diary
    @diary = Diary.find(params[:id])
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @initial_weight = user.initial_weight
    @target_weight = user.target_weight
    @diaries = user.diaries.order("created_at DESC")
    @diaries_reverse = user.diaries
  end
end
 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/diaries/_diary.html.erb
<div class="oya">
  <div class="grid-gallery">
    <% if diary.image.attached? %>
    <%= image_tag diary.image.variant(resize: '330x330'), class: 'message-image' %>
    <% else %>
    <%= image_tag 'noimage.jpeg', size: '300x300'%>
    <% end %>
  </div>
  <div class="grid-day">
    <%= diary.day %>
  </div>
  <% if current_user.id == diary.user_id %>
  <div class="grid-weight">
    体重<%= diary.weight %>kg
  </div>
  <% end %>
  <div class="grid-exercise">
  運動
  </div>
  <div class="grid-exercise-text">
    <span><%= diary.exercise %></span>
  </div>
  <div class="grid-comment">
  コメント
  </div>
  <div class="grid-comment-text">
    <span><%= diary.comment %></span>
  </div>
  <div class="grid-h">
    <%= link_to '詳細', diary_path(diary.id), method: :get, class: "switch" %>
  </div>
  <% if current_user.id == diary.user_id %>
    <div class="grid-i">
      <%= link_to '編集', edit_diary_path(diary.id), method: :get, class: "switch" %>
    </div>
    <div class="grid-j">
      <%= link_to '削除', "/diaries/#{diary.id}", method: :delete, class: "switch" %>
    </div>
  <% end %>
  <div class="grid-k">
    <a href="/users/<%= diary.user.id %>">
      <span>投稿者</span><%= diary.user.nickname %>
    </a>
  </div>
</div>

app/views/diaries/_form.html.erb
<%= form_with(model: diary, local: true) do |form| %>

  <%= render 'layouts/error_messages', model: form.object %>

  <span class="new_text">
    <div class='input-day-wrap'>
    ※必須<%= raw sprintf(
                form.date_select(
                  :day,
                  class:'select-day',
                  id:"day-data",
                  use_month_numbers: true,
                  prompt:'--',
                  start_year: (Time.now.year),
                  end_year: (Time.now.year),
                  date_separator: '%s'),
                "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>
    <div class="new_day_weight">
      <div class="alert">※必須</div>
      <%= form.text_field :weight, placeholder: "体重" %>
      <h1>kg</h1>
    </div>
  </span>
  <label class="form-image">
    <span class="image-file">画像</span>
    <%= form.file_field :image, class: 'hidden' %>
    <div id="image-list"></div>
  </label>
  ※必須/半角数字で入力してください(例:50g/46.7g)
  <span class="new_text">
    <div class="new_day_weight">糖質</div>
    <div class="new_day_weight">タンパク質</div>
    <div class="new_day_weight">脂質</div>
    <div class="new_day_weight">カロリー</div>
  </span>
  <span class="new_text">
    <div class="new_day_weight">
      <%= form.text_field :sugar, placeholder: "" %>
      <h1>g</h1>
    </div>
    <div class="new_day_weight">
      <%= form.text_field :protein, placeholder: "" %>
      <h1>g</h1>
    </div>
    <div class="new_day_weight">
      <%= form.text_field :lipid, placeholder: "" %>
      <h1>g</h1>
    </div>
    <div class="new_day_weight">
      <%= form.text_field :calorie, placeholder: "" %>
      <h1>g</h1>
    </div>
  </span>
  <%= form.text_area :exercise, placeholder: "運動記録", rows: "3" %>
  <%= form.text_area :comment, placeholder: "コメント", rows: "4" %>
  <%= form.submit "登録" %>
<% end %>

app/views/diaries/_top_page.html.erb
<div class="top-page-main">
  <h1>レベル100ダイエット</h1>
  <br><br>
  <h2><span>続けられるダイエット</span>をはじめてみませんか？</h2>
  <br><br><br><br>
  <h3>「レベル100ダイエット」は続けることに特化したアプリケーションです。</p>
  <p>レベルによって日に日に痩せていく自分を実感でき、グラフ化によって自分の成長や食事栄養素も簡単に確認できます。</p>
</div>

<div class="top-page-level top-page-card">
  <h1>レベル機能</h1>
  <p>その日の体重を入力すると体重が減った分だけレベルが上がり、レベル100に到達すると目標達成！</p>
  <%= image_tag 'level.jpeg', size: '700x70' %>
</div>

<div class="top-page-nutrient top-page-card">
  <h1>栄養素機能</h1>
  <p>糖質、タンパク質、脂質、カロリーを入力するとグラフになって表示されます</p>
  <%= image_tag 'nutrient.jpeg' , size: '800x70' %>
</div>

<div class="top-page-anti-aging top-page-card">
  <h1>アンチエイジング効果</h1>
  <p>ダイエットは老化対策にも非常に効果的です</p>
  <p>腹八分目など、一食の摂取カロリーを抑えることで、細胞の死滅を防ぐ機能が強化されることが科学的にわかっています</p>
  <p>また、プチ断食も効果的で食事を16時間取らないでいると、古くなった体の中の細胞が分解され新しい細胞に生まれ変わらすことができます。</p>
  <p>余裕があればぜひ挑戦してみてください！</p>
</div>

<div class="top-page-comment top-page-card">
  <h1>コメント機能</h1>
  <p>詳細からコメントで励まし合うこともできます。</p>
  <p>また、体重は自分の体重は自分しか見れないので安心です。</p>
  <%= image_tag 'comment.jpeg' , size: '800x70' %>
</div>

<div class="top-page-last">
  <p>自分がやり遂げたことで手に入れた自信は、一生無くなりません</p>
  <h1>始める</h1>
  <br><br>
  <%= link_to "新規登録", new_user_registration_path, class: "top-page-sign" %>
  <%= link_to "ログイン", new_user_session_path, class: "top-page-sign" %>
  <br><br><br>
</div>

app/views/diaries/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>登録が完了しました。</h3>
    <a class="btn" href="/">記録一覧へ戻る</a>
  </div>
</div>

app/views/diaries/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>削除が完了しました。</h3>
    <a class="btn" href="/">記録一覧へ戻る</a>
  </div>
</div>

app/views/diaries/edit.html.erb
<div class="contents row">
  <div class="container">
    <h3>編集する</h3>
    <%= render partial: "form", locals: { diary: @diary } %>
  </div>
</div>

app/views/diaries/index.html.erb
<% if user_signed_in? %>
  <%= form_with(url: search_diaries_path, local: true, method: :get, class: "search-form") do |form| %>
    <div class="search-flex">
      <div class='input-day-wrap'>
        日付検索
        <%= raw sprintf(
                form.date_select(
                  :day,
                  class:'select-day',
                  id:"day-data",
                  use_month_numbers: true,
                  prompt:'--',
                  start_year: (Time.now.year),
                  end_year: (Time.now.year),
                  date_separator: '%s'),
                "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
        <%= form.submit "検索", class: "search-btn" %>
      </div>
    </div>
  <% end %>
  
  <div class="contents">
    <div class="big-left">
      <% @diaries.each do |diary| %>
        <%= render partial: "diary", locals: { diary: diary } %>
      <% end %>
    </div>
  </div>
<% else %>
  <%= render partial: "top_page" %>
<% end %>

app/views/diaries/new.html.erb
<div class="contents row">
  <div class="container">

    <h3>登録する</h3>
    <%= render partial: "form", locals: { diary: @diary } %>

  </div>
</div>

app/views/diaries/search.html.erb
<%= form_with(url: search_diaries_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "日付で検索", class: "search-input" %>
  日目
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
<div class="contents">
  <div class="big-left">
    <% @diaries.each do |diary| %>
      <%= render partial: "diary", locals: { diary: diary } %>
    <% end %>
  </div>
</div>

app/views/diaries/show.html.erb
<div class="oya">
  <div class="grid-gallery">
    <% if @diary.image.attached? %>
    <%= image_tag @diary.image.variant(resize: '330x330'), class: 'message-image' %>
    <% else %>
    <%= image_tag 'noimage.jpeg', size: '300x300'%>
    <% end %>
  </div>
  <div class="grid-day">
    <%= @diary.day %>
  </div>
  <div class="grid-weight">
    体重<%= @diary.weight %>kg
  </div>
  <div class="grid-exercise">
  運動
  </div>
  <div class="grid-exercise-text">
    <span><%= @diary.exercise %></span>
  </div>
  <div class="grid-comment">
  コメント
  </div>
  <div class="grid-comment-text">
    <span><%= @diary.comment %></span>
  </div>
  <% if current_user.id == @diary.user_id %>
    <div class="grid-h">
      <%= link_to '編集', edit_diary_path(@diary.id), method: :get %>
    </div>
    <div class="grid-i">
      <%= link_to '削除', "/diaries/#{@diary.id}", method: :delete %>
    </div>
  <% end %>
  <div class="grid-j">
    <a href="/users/<%= @diary.user.id %>">
      <span>投稿者</span><%= @diary.user.nickname %>
    </a>
  </div>
</div>

<div>
  <% chart_datas = [] %>
  <% chart_data1 = [] %>
  <% chart_data2 = [] %>
  <% chart_data3 = [] %>
  <% chart_data4 = [] %>
  <% chart_datas << chart_data1 %>
  <% chart_datas << chart_data2 %>
  <% chart_datas << chart_data3 %>
  <% chart_datas << chart_data4 %>
  <% chart_data1 << "糖質(g)" %>
  <% chart_data1 << @diary.sugar.to_f %>
  <% chart_data2 << "タンパク質(g)" %>
  <% chart_data2 << @diary.protein.to_f %>
  <% chart_data3 << "カロリー(kcal)" %>
  <% chart_data3 << @diary.calorie.to_f %>
  <% chart_data4 << "脂質(g)" %>
  <% chart_data4 << @diary.lipid.to_f %>

  <%= bar_chart chart_datas, width: "1100px", height: "400px", colors: ["#b00", "#666"] %>
</div>

  <div class="container">
    <% if user_signed_in? %>
      <%= form_with(model: [@diary, @comment], local: true) do |form| %>
        <%= form.text_area :text, placeholder: "コメントする", rows: "2" %>
        <%= form.submit "送信" %>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p>
      </strong>
    <% end %>
    <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% @comments.each do |comment| %>
        <p>
          <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
          <%= comment.text %>
        </p>
      <% end %>
    </div>
  </div>

app/views/diaries/update.html.erb
<div class="contents row">
  <div class="success">
    <h3>更新が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
 <ul>
   <% model.errors.full_messages.each do |message| %>
   <li class='error-message'><%= message %></li>
   <% end %>
 </ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Level100Diet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">Level100Diet</a></h1>

        <% if user_signed_in? %>
          <div class="user_nav grid-6">
            <span><%= current_user.nickname %>
              <ul class="user__info">
                <li>
                  <%= link_to "マイページ", "/users/#{current_user.id}" %>
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                </li>
              </ul>
            </span>
            <%= link_to "投稿する", new_diary_path, class: "post" %>
          </div>
        <% else %>
          <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, class: "post" %>
            <%= link_to "新規登録", new_user_registration_path, class: "post" %>
          </div>
        <% end %>
      </div>
    </header>
      <%= yield %>
  </body>
</html>